export const DOMAINS = [
  'AI/ML Engineer',
  'PHP Developer',
  'Data Engineer',
  'Data Scientist',
  'DevOps',
  'MERN Developer',
  'Python Developer',
  'Java Developer',
  'DBA',
  'Cloud Engineer',
  'Network Engineer',
  'Go Lang Developer',
  'Technical Support',
  'Business Analyst',
  '.NET Developer',
  'Data Analytics',
  'QA (Quality Assurance)',
];
